# Generated by Django 5.2.7 on 2025-10-13 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakfastChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('chosen_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupils.dish', verbose_name='Выбранное блюдо')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupils.pupil', verbose_name='Ученик')),
            ],
            options={
                'unique_together': {('pupil', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('option_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_option_1', to='pupils.dish', verbose_name='Вариант завтрака 1')),
                ('option_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_option_2', to='pupils.dish', verbose_name='Вариант завтрака 2')),
            ],
            options={
                'unique_together': {('date',)},
            },
        ),
    ]
