# Generated by Django 5.2.7 on 2025-10-21 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0002_breakfastchoice_dailymenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Название класса', 'verbose_name_plural': 'Названия классов'},
        ),
        migrations.AlterModelOptions(
            name='dailymenu',
            options={'verbose_name': 'Ежедневное меню', 'verbose_name_plural': 'Ежедневное меню'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Завтрак', 'verbose_name_plural': 'Завтраки'},
        ),
        migrations.AlterModelOptions(
            name='pupil',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.CreateModel(
            name='WeeklyBreakfasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(verbose_name='Дата начала недели')),
                ('friday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friday_breakfasts', to='pupils.dish', verbose_name='Пятница')),
                ('monday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_breakfasts', to='pupils.dish', verbose_name='Понедельник')),
                ('pupil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pupils.pupil', verbose_name='Ученик')),
                ('thursday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday_breakfasts', to='pupils.dish', verbose_name='Четверг')),
                ('tuesday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_breakfasts', to='pupils.dish', verbose_name='Вторник')),
                ('wednesday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_breakfasts', to='pupils.dish', verbose_name='Среда')),
            ],
        ),
        migrations.DeleteModel(
            name='BreakfastChoice',
        ),
    ]
